[[section-introduction-and-goals]]
== Introduction and Goals

The aim of the project is to create a decentralized routes management system based on the <<solid_definition,SOLID>> framework allowing users to control their own personal data.  

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****
- Our application will consist of a decentralized architecture where user's data is separated from the app.
- Users can store their routes in their own <<pod_definition, PODs>>.
- Users can visualize the routes stored on a map.
- The app will allow a user to share pictures, videos or information about a route with other friends.
- A user can get notifications when some friend shares a route with him.
- Users can have groups of friends to share the routes with.
- It should be possible to view routes loaded by users that are using a different app, so interoperability with other route management systems should be taken into account.

==== Optional Requirements
- The system could be mobile compatible.
- Users can share their routes in real time.


=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header", cols="0,0,4,3"]
|===
|Priority| Goal         | Motivation | Scenarios
|1| Usability |The app must be easy to use by non-technical people. | As a new user, I want to be able to use the app without needing any external help.
|2| Privacy    | Users must be the owners of their own data. | As a user, I want to be able to choose where I want my own data to be.
|3| Effectiveness | Users must be able to share their routes according to the functionalities of the system. | As a user, I want to be able to share my routes with my contacts.
|4| Interoperability | The system must be able to communicate with other similar SOLID apps | As a user, I want to be able to share the routes loaded in my application with other similar SOLID apps.

|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2"]
|===
|Role/Name|Expectations
| Developers | _Develop an application fulfilling the requierements that allow us to pass the course._
| SOLID Developers | _Help us with our doubts concerning the SOLID specifications._
| Course professors | _Evaluate our work and follow our progress throughout the course._
| End users | _Be able to use our application and take advantage of the functionalities._
| Project sponsor | _Spread decentralized applications so as they get known by the community._
|===

