[[section-system-scope-and-context]]
== System Scope and Context

Our routes application will be managed following the SOLID standards. In other
words, this tool will be decentralized which means that This application will allow each user to store and share their own personal
routes without fearing any company using their data in ways they have not approved. However, we have some limitations, for example it would be more difficult
to use and manage. Despite of this facts, this application is supposed to be interoperable, which means that it does not matter which application you use
the data is the same for all of them.

=== Business Context

[plantuml,"Business context",png]
----
include::diagrams/03-01_BusinessContext.puml[]
----


[options="header", cols="0,4"]
|===
|Element | Role
| User | User of the application
| Viade | Our application of ViaDe
| User's POD | Personal storage of the user
| Other User Viade | External application which the user can share and receive routes
| imaps | API of the maps
|===

=== Technical Context

[plantuml,"Technical Context",png]
----
include::diagrams/03-02_TechnicalContext.puml[]
----
[options="header", cols="0,4"]
|===
|Partner | Role
| Red arrow | Request made to a system, in order to know the direction of the requests.
| Blue arrow | Response that a system provides for a given request, in order to know the direction of the information.

| Users | People wanting to store and share their routes with control over their storage.
| Viade | Our application that is supposed to be interoperable thanks to the use of Solid.
| POD | Each user has a personal pod which stores all his information
|===

