[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Introduction

In this section you will find the software decisions and solutions strategies taken in order to ensure a great system's architecture


=== Decisions
The project is developed using the following technologies:

[options="header", cols="0,4", title="Technologies used for developing"]
|===
|Technology | Purpose
| ReactJS  | We will use this JavaScript library to build the user interfaces
| Solid | We have to store the user data in a Solid POD
|Node JS | We will use it for the server-side
|===

[options="header", cols="0,4", title="Technologies used for developing"]
|===
|Technology | Purpose
| TBD | TBD
|===

[options="header", cols="0,4", title="Continuous Integration Services"]
|===
|Technology | Purpose
| Travis  | Automatically build code, test code and provide and inmediate feedback of the success of the changes
| Coveralls | Hosted analysis tool which provide stadistics about our code coverage
|Code Quality | Write quality code and make it understandable
|===