[[section-building-block-view]]


== Building Block View

[plantuml,"Whitebox overall system",png]
----
include::diagrams/05-01_whiteboxOverallSystem.puml[]
----

Motivation::

The system must handle routes defined externally, communicate with a Solid POD
where they are stored and present a user interface built with React. These are
three separated responsibilities and each of them can be contained in its own
module.

Contained Building Blocks::

[options="header"]
|==============================
| Building block       | Description
| React module             | Offers an interface to the system for the final user.
| Parser module | Provides methods to parse files.
| Store module | Redux store in charge of state of the whole application.
| Middlewares module | Middlewares to perform async operations.
| Solid module        | Offers an interface to the Solid POD.
|==============================


Important Interfaces::

_<Description of important interfaces>_

=== Redux module

Responsibility::

Offers an interface into the system for the final user.

Quality/Performance Characteristics::

The graphical interface must accord to the Solid style guide. It must also be
responsive enough for final users to interact with the system without problem.

Directory/File Location::

_WIP_

Fulfilled Requirements::

_WIP_

Open Issues/Problems/Risks::

_WIP_

==== Map module

Responsibility::

Provides a map for the routes to be represented on.

Interface::

Provides an interface to show and interact with routes.

Quality/Performance Characteristics::

The maps must be precise and expressive enough for the routes to be easily
interpreted by as many final users as possible.

Directory/File Location::

_WIP_

Fulfilled Requirements::

_WIP_

Open Issues/Problems/Risks::

_WIP_




==== Route interpretation

Responsibility::

Deals with the routes format.

Interface::

Offers representable routes.

Quality/Performance Characteristics::

Handling of routes must be responsive enough to not affect the flow of the
application.

Directory/File Location::

_WIP_

Fulfilled Requirements::

_WIP_

Open Issues/Problems/Risks::

_WIP_


==== Solid module

Responsibility::

Knows the Solid protocol and interacts directly with PODs.

Interface::

[options="header"]
|==============================
| Method                                  | Description
| getRoutesFolder(userWebId)              | Gets the URL of the routes storage as a string
| uploadRouteToPod(route, userWebId)      | Uploads a route object to the user's POD
| getRouteFromPod(routeName, userWebId)   | Gets a route from the user's POD by name
| getRoutesFromPod(userWebId)             | Gets a list with all the routes from the user's POD
| clearRouteFromPod(routeName, userWebId) | Deletes a route from the user's POD by name
| clearRoutesFromPod(userWebId)           | Deletes all routes from the user's POD
|==============================

Quality/Performance Characteristics::

Must fit the standards of Solid data representation and exploit the benefits of
linked data.

Directory/File Location::

`src/solid/`

Fulfilled Requirements::

Basic interface to interact with profile and routes stored in a user's POD.

Open Issues/Problems/Risks::

_WIP_
