[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

We only know very abstract and few details about these actions at the moment, that's why we have decided to represent these actions with a basic activitity diagram.

=== Upload a route

One action that we know is the action of uploading a route from the user´s storage to the user's pod.

* A user will click a button or similar to import the route.
* Then, he will choose the rout to upload from his files system.
* Finally, the route will be uploaded to the user's POD and shown in our application.

[plantuml,"Uploading a route",png]
----
include::diagrams/06-01_uploadRoute.puml[]
----

=== Share a route

A user can also share a route with any friend he wants. 

. Firstly, the user must select the route he want to share.
. Then, he must select the friend he wants to share the route with.
. Finally, the route must be added to the friend´s POD and be able to be displayed.

[plantuml,"Sharing a route",png]
----
include::diagrams/06-02_shareRoute.puml[]
----

=== TODO
