[[section-runtime-view]]
== Runtime View
The main runtime views of the application are the ones in charge of dealing with the routes and the user profile data. These views will be explained in detail in the following sections.

=== Activity diagrams

==== Upload a route

The user will be able to upload a route to his own POD.

. A user will click a button on the "Upload route".
. The user will write the name of the route and a description.
. Then, he will choose the route to upload from his files system or he can write it by hand in the "Position" text area.
. After that, he can attach a picture or a video
. Finally, the route will be uploaded to the user's POD and shown in our application.

[plantuml,"Uploading a route",png]
----
include::diagrams/06-01_uploadRoute.puml[]
----

==== Share a route

A user can share a route to one of his friends.

. Firstly, the user must select the route he want to share.
. Then, he must select the friend he wants to share the route with.
. Finally, the route must be added to the friend's POD and be able to be displayed.

[plantuml,"Sharing a route",png]
----
include::diagrams/06-02_shareRoute.puml[]
----

==== Comment a route
A user will be able to post a comment in a route.

. First, the user will click on the desired route to comment.
. Then, the user will write his comment.
. Finally, when the comment its written and saved, the route will have the comment in it.

[plantuml,"Commenting a route",png]
----
include::diagrams/06-03_commentRoute.puml[]
----

==== Accessing a friend profile
Our users will be able to access from the Viade app to any of their friends profile.

. First, the user should click on "My Profile"
. Then, click on any of their friends of their friend list.

[plantuml,"Accessing friend profile",png]
----
include::diagrams/06-04_accessingFriend.puml[]
----


==== Checking notifications

In order to check for new notifications is quite simple:

. First the user needs to click on the bell symbol of the NavBar.
. Now, all the notifications will load, so the user can check them
. Once he finish, the user can click on "Accept all", so all the notifications will be deleted and shared routes will be loaded.

[plantuml,"Checking Notifications",png]
----
include::diagrams/06-05_CheckingNotifications.puml[]
----

==== Changing the application language

As all the user are not going to be English speakers, we add more languages, so this problem could be overcome. However, to change the locale (language) we need to:

. First, the user needs to click on the "Settings" option of the NavBar.
. After that, the user needs to click on "Available Languages".
. Now, a new drop down menu will appear with all the possible locales ("languages"), so the user only needs to select one of them.
. Finally, the application will refresh with the correct language.

[plantuml, "Changing the application language", png]
----
include::diagrams/06-06_ChangeLanguage.puml[]
----

==== Changing the application theme
Although our main audience/users will not have any vision deficiency (color-blindness), we have implemented a small support for those who have it. Also, we have added some extra customization themes.
In order to change the theme the user needs to do the following steps:

. First click on "Themes" in the NavBar.
. A new drop down menu will appear with all the possible theme options.
. Select the desired theme.

[plantuml, "Changing the application theme", png]
----
include::diagrams/06-07_ThemesChange.puml[]
----





=== Sequence diagrams

The previous diagrams describe some actions but at a very high-level of detail. Now we are going to focus on some more _difficult_ actions trying to explain them more in detail, at a low level.

==== Loading routes from POD

[plantuml,"Loading routes",png]
----
include::diagrams/06_SD_LoadRoutes.puml[]
----

Since it is a bit complex diagram, we are going to explain it in detail:

. A message is sent from the NavBar to the Redux store in order to load the routes.
. The store dispatches the proper action.
. A request for loading the routes is called and intercepted by the middleware.
. The middleware is in charge of actually loading the routes asynchronously. Meanwhile, the reducer gives a response to the request.
. Once the routes are loaded, there are two possible scenarios: everything worked or some error occurred.
If everything worked, a load routes success actions is dispatched from the store, and the state is updated with the routes.
On the other hand, if an error occurred while loading the routes, an error action is dispatched and the state is updated.
. Finally, the state is received by the NavBar (whole application).

==== Displaying a route in the map

[plantuml,"Display route",png]
----
include::diagrams/06_SD_DisplayRoute.puml[]
----

In this diagram we can perfectly observe again the redux architecture:

. The user clicks on a route and an event is triggered.
. An action is dispatched and the reducer updates the state.
. Once the state is updated, the map component receives the positions of the route and the route is displayed.

==== Uploading a route

[plantuml,"Upload route",png]
----
include::diagrams/06_SD_UploadRoute.puml[]
----

. Firstly, the user enter in UploadRoute and fills in the data about a route.
. Behind that action, the GPXParser parses the file into an array of latitudes and longitudes.
. Then, all the Redux process starts.
. The RouteReducer calls uploadRouteToPod and before writing the route in the pod we ask the parser to give us the route in JsonLD.
. Finally, the route in JsonLD is written in the POD.

==== Sharing a route with a friend

[plantuml,"Sharing a route",png]
----
include::diagrams/06_SD_ShareRoutes.puml[]
----

In this diagram, we do not take into account the previous actions before the actual method of sharing in order to make the diagram as simple as possible, and focus on the SOLID part.
 
. First of all, we see that the RouteReducer calls the method for sharing a route.
. Then, we ask the parser for a notification in the correct format.
. The notification is written in friend´s viade/inbox.

==== Accepting a notification

[plantuml,"Accepting a notification",png]
----
include::diagrams/06_SD_AcceptNotification.puml[]
----

After a route has been shared with us, we need to do the following actions:

. We need to go to the Notifications view and click "Accept all".
. Then, we check /viade/inbox for new notifications.
. We read the new notification from the POD and we ask the parser to give us the routeUri.
. Finally, the routeUri is written in the corresponding file in /viade/shared.


