[[section-runtime-view]]
== Runtime View
The main runtime views of the application are the ones in charge of dealing with the routes and the user profile data.

These views will be explained in detail in the following sections.

=== Activity diagrams

==== Upload a route

The user will be able to upload a route to his own POD.

. A user will click a button on the "Upload route".
. The user will write the name of the route and a description.
. Then, he will choose the route to upload from his files system or he can write it by hand in the "Position" text area.
. After that, he can attach a picture or a video 
. Finally, the route will be uploaded to the user's POD and shown in our application.

[plantuml,"Uploading a route",png]
----
include::diagrams/06-01_uploadRoute.puml[]
----

==== Share a route

A user can share a route to one of his friends. 

. Firstly, the user must select the route he want to share.
. Then, he must select the friend he wants to share the route with.
. Finally, the route must be added to the friend´s POD and be able to be displayed.

[plantuml,"Sharing a route",png]
----
include::diagrams/06-02_shareRoute.puml[]
----

==== Comment a route
A user will be able to post a comment in a route.

. First, the user will click in the desired route to comment.
. Then, the user will write his comment.
. Finally, when the comment its written and saved, the route will have the comment in it.

[plantuml,"Commenting a route",png]
----
include::diagrams/06-03_commentRoute.puml[]
----

==== Accessing a friend profile
Our users will be able to access from the viade app to any of their friends profile.

. First, the user should click on "My Profile"
. Then, click on any of their friends of their friend list.

[plantuml,"Accessing friend profile",png]
----
include::diagrams/06-04_accessingFriend.puml[]
----

=== Sequence diagrams
[plantuml,"Loading routes",png]
----
include::diagrams/06_SD_LoadRoutes.puml[]
----

