@startuml Business Context
rectangle Viade
rectangle "Other User Viade" as ViaDe2
database "User's POD" as pod

() "Maps API" as imaps

:User: <--> Viade : View routes on the \n map & share routes
Viade --> pod : Store routes
pod --> Viade : Load stored routes
Viade <-right- imaps : Get the API maps services
Viade -left-> ViaDe2 : Share information \n about the route

@enduml

