@startuml

node "Viade"
database "POD"
interface "Maps API" as maps
actor User

Viade <-[#blue]up- POD:JsonLD
Viade -up-> POD:HTTP

User -> Viade:HTTP
User <-[#blue]up- Viade:HTTP

Viade-right-> maps:HTTP
Viade <-[#blue]right- maps:HTTP

@enduml
