@startuml Business Context
rectangle ViaDe
rectangle "Other User ViaDe" as ViaDe2
database "User's POD" as pod

() "Maps API" as imaps

:User: --> ViaDe : View routes on the \n map & share routes
ViaDe --> pod : Store routes
pod --> ViaDe : Load stored routes
ViaDe -right-> imaps : Get the API maps services
ViaDe -left-> ViaDe2 : Share information \n about the route
@enduml