@startuml

rectangle ViaDe {
    [Solid module] as solidmod
    [Map module] as map
    [Route interpretation] as routes
    [React] as react
}

database "User's POD" as pod

() "Maps API" as imaps

:User: --> react
react --> map
map --> routes
map --> imaps
routes --> solidmod
react --> solidmod
solidmod --> pod

@enduml
