@startuml

rectangle ViaDe {
    [GUI Components] as react
    [Parser] as parser 
    [Middlewares] as middlewares
    [Redux] as store 
    [Solid] as solid
    [Utils]
}

database "User's POD" as pod

() "Maps API" as imaps

:User: --> react

react <-- store
react --> store

react --> middlewares

parser <- react
parser -> react

middlewares -> store

store -> solid
store <- solid

solid -> pod
solid <- pod

react -> imaps
imaps -> react







@enduml
