@startuml

rectangle Redux {
    node "Store" {
        [Dispatcher] as dispatcher
        folder "Reducers" as reducers {
            [AuthReducer] as authReducer
            [RouteReducer] as routeReducer
            [UserReducer] as userReducer
            [RootReducer] as rootReducer
            [LoadReducer] as loadReducer
            [LocaleReducer] as localeReducer
        }
        [State] as state
    }

    folder "Actions" as actions {
    [AuthActions] as authActions
    [RouteActions] as routeActions
    [UserActions] as userActions
    [LoadActions] as loadActions
    [LocaleActions] as localeActions
}
}



[App] as app 

app -up-> actions :event
actions -up-> dispatcher :action
dispatcher -> reducers :dispatch
state -> reducers :oldState
reducers -up-> [Solid]
[Solid] -down-> reducers
reducers -down-> state :newState
state -down-> app :newState










@enduml
