title A user shares a route with a friend - Activity Diagram

start

:Go to "My Routes section";

:Select a route to share;

:Click "Share" button;

:Select a friend;

:Click "Share" and the route is added to friend's POD;

stop

