title Load routes - Sequence Diagram

@startuml

participant NavBar as nb
participant ReduxStore as rs
participant RouteActions as ra
participant RouteReducer as rr
participant RouteMiddleware as rm
participant Solid.js as s
participant parser.js as pa
database POD as p

activate nb
nb -> rs: loadRoutesRequest()
activate rs
rs -> ra: dispatch(loadRoutesRequest())
activate ra
ra -> rm: loadRoutesRequest()
destroy ra
activate rm
rm -> s: getRoutesFromPod(userwebid)
activate s
rm -> rr: loadRoutesRequest()
activate rr
rr --> rs: state
destroy rr
loop for each user´s routes
    s -> p: readFile()
    activate p
    p --> pa: route in JsonLd
    activate pa
    pa --> s: route in json
    destroy pa
end
destroy p
...
alt routes successfully loaded
s --> rm: routes
destroy s
rs -> ra: dispatch(loadRoutesSuccess(routes))
activate ra
ra -> rr: loadRoutesSuccess(routes)
activate rr
destroy ra
rr -> rr: updateState(routes)
rr --> rs: state with routes updated
destroy rr
else error at loading routes
s --> rm: error
destroy s
rs -> ra: dispatch(loadRoutesError(error))
activate ra
ra -> rr: loadRoutesError(error)
activate rr
destroy ra
rr -> rr: updateState(error)
rr --> rs: state updated
destroy rr
end
destroy rm
rs --> nb: state
destroy rs
legend right
line = method
dash line = data
endlegend

@enduml
